version: "3.5"

services:
  neko-rooms:
    build: "./"
    restart: "unless-stopped"
    privileged: true
    environment:
      - "TZ=Europe/Vienna"
      - "NEKO_ROOMS_EPR=59000-59049"
      - "NEKO_ROOMS_NAT1TO1=10.8.0.1" # IP address of your server
      - "NEKO_ROOMS_INSTANCE_URL=http://10.8.0.1:8080/" # external URL
    volumes:
      - ./data/storage:/data
      - ./data/docker:/var/lib/docker
      - ./data/certs:/certs
    ports:
      - 8080:80
      - 59000-59049:59000-59049/udp
